# Generated by Django 4.2.3 on 2023-09-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0008_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(max_length=200),
        ),
    ]
