# Generated by Django 4.2.3 on 2023-09-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0009_alter_messages_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Blog',
        ),
    ]
