# Generated by Django 4.2.3 on 2023-09-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0015_alter_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
