# Generated by Django 4.2.3 on 2023-09-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0021_mensaje_messageid_alter_mensaje_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='messageid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rmensaje', to='AppWeb.blog'),
        ),
    ]
