# Generated by Django 4.2.3 on 2023-09-05 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0023_remove_mensaje_messageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='messageid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rmensaje', to='AppWeb.blog'),
        ),
    ]
