# Generated by Django 4.2.3 on 2023-09-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0024_mensaje_messageid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='messageid',
        ),
    ]
