# Generated by Django 4.2.3 on 2023-09-05 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppWeb', '0025_remove_mensaje_messageid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='user',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='message_campo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppWeb.blog'),
        ),
        migrations.CreateModel(
            name='Mensaje2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
