# Generated by Django 4.2.3 on 2023-09-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0026_remove_mensaje_user_mensaje_message_campo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='message_campo',
            field=models.TextField(null=True),
        ),
    ]
