# Generated by Django 4.2.3 on 2023-09-05 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppWeb', '0027_alter_mensaje_message_campo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='message_campo',
        ),
        migrations.RemoveField(
            model_name='mensaje2',
            name='user',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensaje2',
            name='message_campo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje2',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppWeb.blog'),
        ),
    ]
