# Generated by Django 4.2.3 on 2023-09-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0029_remove_mensaje_user_remove_mensaje2_message_campo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='mensaje',
            new_name='blog',
        ),
    ]
