# Generated by Django 4.2.3 on 2023-09-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0034_blog_imagen_blog2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesblog'),
        ),
    ]
