# Generated by Django 4.2.3 on 2023-09-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0035_alter_blog_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(default=2, upload_to='imagenesblog'),
            preserve_default=False,
        ),
    ]
