# Generated by Django 4.2.3 on 2023-09-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0038_blog_imagen_blog2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, default=2, upload_to='blogimg/'),
            preserve_default=False,
        ),
    ]
