# Generated by Django 4.2.3 on 2023-09-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0045_alter_blog_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog2',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comprador',
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
        migrations.RemoveField(
            model_name='mensaje2',
            name='user',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imagen',
        ),
        migrations.DeleteModel(
            name='Blog2',
        ),
        migrations.DeleteModel(
            name='Mensaje2',
        ),
    ]
