# Generated by Django 4.2.3 on 2023-09-07 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppWeb', '0048_imagen_blog_alter_imagen_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='blog',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to=settings.AUTH_USER_MODEL),
        ),
    ]
