# Generated by Django 4.2.3 on 2023-09-07 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0052_imagen_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='Blog',
            new_name='blog',
        ),
    ]
