# Generated by Django 4.2.3 on 2023-09-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0056_blog_imagen_blog3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imagen',
        ),
        migrations.DeleteModel(
            name='Blog3',
        ),
    ]
