# Generated by Django 4.2.3 on 2023-09-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0057_remove_blog_imagen_delete_blog3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
