# Generated by Django 4.2.3 on 2023-09-09 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0059_cisne'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='cisne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cismensaje', to='AppWeb.cisne'),
        ),
    ]
