# Generated by Django 4.2.3 on 2023-09-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0060_mensaje_cisne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='blog',
        ),
    ]
