# Generated by Django 4.2.3 on 2023-09-09 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0063_cisnemensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='user',
        ),
        migrations.AlterField(
            model_name='cisnemensaje',
            name='cisne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cisnemensajes', to='AppWeb.cisne'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Blog2',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
