# Generated by Django 4.2.3 on 2023-09-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0067_remove_mensaje_cisne_mensaje_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cisnemensaje',
            name='cisne',
        ),
        migrations.RemoveField(
            model_name='cisnemensaje',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cisne',
        ),
        migrations.DeleteModel(
            name='CisneMensaje',
        ),
    ]
