# Generated by Django 4.2.3 on 2023-09-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0069_blog2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='user',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
