# Generated by Django 4.2.3 on 2023-09-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0071_rename_blog2_blog_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='titulomessage',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
