# Generated by Django 4.2.3 on 2023-09-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0072_blog_titulomessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titulo',
            new_name='titulofoto',
        ),
    ]
