# Generated by Django 4.2.3 on 2023-10-02 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppWeb', '0075_mensajeuser_userm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeuser',
            name='userm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajessuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
