# Generated by Django 4.2.3 on 2023-10-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0076_alter_mensajeuser_userm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajeuser',
            old_name='userm',
            new_name='mensajeuser',
        ),
    ]
