# Generated by Django 4.2.3 on 2023-10-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0077_rename_userm_mensajeuser_mensajeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajeuser',
            name='mensajeuser',
        ),
    ]
