# Generated by Django 4.2.3 on 2023-10-03 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppWeb', '0078_remove_mensajeuser_mensajeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajeuser',
            name='user',
        ),
        migrations.AddField(
            model_name='mensajeuser',
            name='user_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajeuser',
            name='user_transmitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
