# Generated by Django 4.2.3 on 2023-10-03 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0079_remove_mensajeuser_user_mensajeuser_user_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajeuser',
            old_name='user_receiver',
            new_name='user',
        ),
    ]
