# Generated by Django 4.2.3 on 2023-10-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0081_remove_mensajeuser_titulomessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeuser',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
