# Generated by Django 4.2.3 on 2023-11-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0082_alter_mensajeuser_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeuser',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
