# Generated by Django 4.2.3 on 2023-11-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0083_alter_mensajeuser_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeuser',
            name='fecha',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
