# Generated by Django 4.2.3 on 2023-11-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0084_alter_mensajeuser_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeuser',
            name='hora',
            field=models.TimeField(auto_now_add=True, default='17:34:55.022636'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensajeuser',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
