# Generated by Django 4.2.3 on 2023-09-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_imagen_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
