# Generated by Django 4.2.3 on 2023-09-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
