# Generated by Django 4.2.3 on 2023-09-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_delete_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
